steps:
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.1.0
    id: unit-test
    env:
      - TELEPORT_ETCD_TEST="yes"
    entrypoint: '/bin/bash'
    args: 
      - '-c'
      - '(make run-etcd &); sleep 1; make test'
    timeout: 15m
timeout: 15m
options:
  machineType: 'E2_HIGHCPU_32'
  
